// *** BG:SOD - Coldhearth Dungeon - Check for enemy presence in room ***

IF
  OR(2)
    Detect([PC])
    GlobalGT("a7!check2", "MYAREA", 0)
  Global("a7!check1", "MYAREA", 0)
THEN
  RESPONSE #100
    SetGlobal("a7!check1", "MYAREA", 1)
END

IF
  !ActuallyInCombat()
  !Detect([ENEMY])
  Global("a7!check1", "MYAREA", 1)
THEN
  RESPONSE #100
    SetGlobal("a7!check1", "MYAREA", 2)
    TriggerActivation(Myself, FALSE)
END
