// *** Golem construction cutscene (12 h) ***

IF
  True()
THEN
  RESPONSE #100
    // CutSceneId("a7!smdlg")
    CutSceneId(Myself)
    ClearAllActions()
    FadeToColor([30.0],0)
    Wait(2)
    AdvanceTime(3600) // 12 hours
    SetToken("A7_HOURS", @40002)  // twelve
    JumpToObject(LastSummonerOf(Myself))  // Hack: needed or helper creature is relocated to [0.0] of the map
    FadeFromColor([30.0],0)
    Wait(2)
    StartDialogueNoSet(LastSummonerOf(Myself))
END
