// *** Tweaks: Add teleport ability ***

// Teleport
COPY ~%MOD_FOLDER%/spells/a7!in08.spl~ ~override~
  SAY NAME1 @20070  // Teleport
  SAY UNIDENTIFIED_DESC @20071  // ...

COPY ~%MOD_FOLDER%/spells/a7!in08b.bam~ ~override~
     ~%MOD_FOLDER%/spells/a7!in08a.eff~ ~override~
     ~%MOD_FOLDER%/spells/a7!in08a.spl~ ~override~


COPY_EXISTING ~a7!glfl1.cre~ ~override~
              ~a7!gsfl1.cre~ ~override~
              ~a7!glfl2.cre~ ~override~
              ~a7!gsfl2.cre~ ~override~
              ~a7!glfl3.cre~ ~override~
              ~a7!glfl4.cre~ ~override~
              ~a7!glcl1.cre~ ~override~
              ~a7!gscl1.cre~ ~override~
              ~a7!glcl2.cre~ ~override~
              ~a7!gscl2.cre~ ~override~
              ~a7!glcl3.cre~ ~override~
              ~a7!glcl4.cre~ ~override~
              ~a7!glst1.cre~ ~override~
              ~a7!gsst1.cre~ ~override~
              ~a7!glst2.cre~ ~override~
              ~a7!gsst2.cre~ ~override~
              ~a7!glst3.cre~ ~override~
              ~a7!glst4.cre~ ~override~
              ~a7!glir1.cre~ ~override~
              ~a7!gsir1.cre~ ~override~
              ~a7!glir2.cre~ ~override~
              ~a7!gsir2.cre~ ~override~
              ~a7!glir3.cre~ ~override~
              ~a7!glir4.cre~ ~override~
              ~a7!glmi1.cre~ ~override~
              ~a7!gsmi1.cre~ ~override~
              ~a7!glmi2.cre~ ~override~
              ~a7!gsmi2.cre~ ~override~
              ~a7!glmi3.cre~ ~override~
              ~a7!glmi4.cre~ ~override~
              ~a7!glad1.cre~ ~override~
              ~a7!gsad1.cre~ ~override~
              ~a7!glad2.cre~ ~override~
              ~a7!gsad2.cre~ ~override~
              ~a7!glad3.cre~ ~override~
              ~a7!glad4.cre~ ~override~
              ~a7!glmg.cre~ ~override~
              ~a7!glbo.cre~ ~override~
              ~a7!glbr.cre~ ~override~
              ~a7!glic.cre~ ~override~
              ~a7!glma.cre~ ~override~
              ~a7!glru.cre~ ~override~
              ~a7!gldo.cre~ ~override~
              ~a7!glbd.cre~ ~override~
  ADD_KNOWN_SPELL ~a7!in08~ #0 ~innate~   // Teleport
  ADD_MEMORIZED_SPELL ~a7!in08~ #0 ~innate~
BUT_ONLY IF_EXISTS

ACTION_IF (GAME_IS_IWDEE) BEGIN
  COPY_EXISTING ~a7!gmir2.cre~ ~override~
    ADD_KNOWN_SPELL ~a7!in08~ #0 ~innate~   // Teleport
    ADD_MEMORIZED_SPELL ~a7!in08~ #0 ~innate~
  BUT_ONLY IF_EXISTS
END
