// *** BG:SOD - Ruins of Kanaglym (Fugue Portal) - Check for enemies presence in room ***

IF
  OR(3)
    Detect([PC])
    GlobalGT("a7!check1", "MYAREA", 0)
    GlobalGT("a7!check2", "MYAREA", 0)
  Global("a7!check3", "MYAREA", 0)
THEN
  RESPONSE #100
    SetGlobal("a7!check3", "MYAREA", 1)
END

IF
  !ActuallyInCombat()
  !Detect([ENEMY])
  Global("a7!check3", "MYAREA", 1)
THEN
  RESPONSE #100
    SetGlobal("a7!check3", "MYAREA", 2)
    TriggerActivation(Myself, FALSE)
END
