// *** Trigger script: Elder Brain mass in the ruined temple of Cyric (bottom part) ***

IF
  Clicked([ANYONE])
  Range(LastTrigger, 20)
  OR(2)
    Global("A7!GolemAbility", "GLOBAL", 0)
    !Global("A7!BrainTissue", "MYAREA", 0)
THEN
  RESPONSE #100
    DisplayStringHead(Myself, %infoText%)  // A gelatinous, faintly glowing substance burbles and burps as it oozes through this collection of glass and metal tubes.
END
