// *** Golem construction cutscene (36 h) ***

IF
  True()
THEN
  RESPONSE #100
    // CutSceneId("a7!smdlg")
    CutSceneId(Myself)
    ClearAllActions()
    FadeToColor([30.0],0)
    Wait(2)
    AdvanceTime(10800)  // 36 hours
    SetToken("A7_HOURS", @40004)  // thirty-six
    JumpToObject(LastSummonerOf(Myself))  // Hack: needed or helper creature is relocated to [0.0] of the map
    FadeFromColor([30.0],0)
    Wait(2)
    StartDialogueNoSet(LastSummonerOf(Myself))
END
