// *** Cespenar - Restore tome fragments ***

IF
  Global("A7!RestoreTome", "GLOBAL", 1)
  Global("ImpForgeStuff", "GLOBAL", 1)
THEN
  RESPONSE #100
    SetGlobal("A7!RestoreTome", "GLOBAL", 0)
    SetGlobal("ImpForgeStuff", "GLOBAL", 0)
    SetGlobal("ItemMaker", "GLOBAL", 999) // just to let cespenar use his current post-forge dlg
    GiveItemCreate("a7!tom06", Player1, 0, 0, 0)
    StartDialogueNoSet(Player1)
END
