// *** Add items, tomes, etc. to containers, creatures and stores ***

// Scattering items across the world: items and their locations are listed in 2da tables
ACTION_IF (GAME_IS ~bgee eet~) BEGIN
  LAF DISTRIBUTE_ITEMS STR_VAR table = EVAL ~%MOD_FOLDER%/tables/items_bg1.2da~ END
END

ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
  LAF DISTRIBUTE_ITEMS STR_VAR table = EVAL ~%MOD_FOLDER%/tables/items_bg2.2da~ END
END
